import type { MetadataRoute } from 'next'

import { PRIMARY_BRAND_COPY } from '@/domain/copy'

/**
 * Web App Manifest — served at /manifest.webmanifest.
 *
 * Colours come from the production design tokens in app/globals.css, which are
 * the Figma-verified values; no hex is invented here.
 *   theme_color       --color-accent  #6C43F3  (RETURN Purple)
 *   background_color  --color-canvas  #F7F7FA
 *
 * start_url is "/", which the app already routes correctly: middleware sends a
 * signed-out visitor to /login, the (app) layout sends an unfinished profile to
 * /onboarding, and everyone else lands on /journey. PWA gets no separate login
 * flow of its own.
 *
 * Icons are the official RETURN Loop Mark, generated by scripts/build-icons.mjs
 * from the same geometry as src/components/brand/loop-mark.tsx.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: PRIMARY_BRAND_COPY.wordmark,
    short_name: PRIMARY_BRAND_COPY.wordmark,
    description: PRIMARY_BRAND_COPY.subline,
    lang: 'ko',
    dir: 'ltr',
    display: 'standalone',
    orientation: 'portrait',
    start_url: '/',
    scope: '/',
    theme_color: '#6C43F3',
    background_color: '#F7F7FA',
    categories: ['lifestyle'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      {
        src: '/icons/icon-maskable-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/icons/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  }
}
